### ISSUE TITLE
Support Yandex Browser

### ISSUE THREAD

**Issue by danilvalov** [crucifyer/css-browser-selector#2]
Please, add support YaBrowser to script:

```
    ...

    /* Yandex Browser */
    (/yabrowser\/(\d+)\.(\d+)/.test(ua) && (re = RegExp)) ?
    g + ' yandex yandex' + re.$1 + ' yandex' + re.$1 + '_' + re.$2 :

    ...
```

About Yandex Browser: https://browser.yandex.ru

**Comment by crucifyer** [comment]
hi, yandex browser engine is blink (chrome)
why need css selecting?

current chrome == opera == yandex
this project for css design.
if add yandex then maybe more confuse.

ps. evergreen browsers no more need version number for css design

**Comment by danilvalov** [comment]
Hi.

You added Opera selector to your script, though it is also blink.

I need yandex browser selector for it:
![](http://i.imgur.com/Evu5dFP.png)

**Comment by crucifyer** [comment]
opera selecting is "webkit chrome win js landscape pc"
code was very old.

I renamed opera to oldopera.
and blink browsers opera, yandex name added.
opera will "webkit chrome opera win js landscape pc"
yandex will "webkit chrome yandex win js landscape pc"

mobile browser not selecting chrome.

patched code can selecting this.

.safari img.safari { display:block; }
.chrome img.chrome { display:block; }
.yandex img.safari { display:none; }
.yandex img.chrome { display:none; }
.yandex img.yandex { display:block; }
